_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (180000,)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 1000
  IMG_PER_BATCH_LABEL: 32
  IMG_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 4.6
  RANDOM_DATA_SEED: 1 # 0 to use SUP_PERCENT, 1 to use RANDOM_DATA_SEED_PATH
  RANDOM_DATA_SEED_PATH: 'dataseed/alien-barley-labeled.json'
  FILTER_EMPTY_ANNOTATIONS: False
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("alien_barley_train",)
  TEST: ("alien_barley_unlabeled",)
  #TEST: ("alien_barley_test", "alien_barley_unlabeled",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  UNSUP_REG_LOSS_WEIGHT: 1.0
TEST:
  EVAL_PERIOD: 2000
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT: # scale jittering (follow soft teacher)
  MIN_SIZE_TRAIN: (400, 1200)
  MIN_SIZE_TRAIN_SAMPLING: "range"
